
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bksakzulantqzfpvysfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrc2FrenVsYW50cXpmcHZ5c2ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MjcyMzMsImV4cCI6MjA2MjEwMzIzM30.vD8rxCaVQc9_-lNJXmY5fLU32P1atY-NR2QLL4lBQeo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
